sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - build-essential
    - clang
    - fakeroot
    - g++-4.8
    - git
    - libgnome-keyring-dev
    - xvfb
    - rpm
    - libxext-dev
    - libxtst-dev
    - libxkbfile-dev
branches:
  only:
  - master
  - /ci-.*/
  - /stable.*/   
matrix:
  include:
  - os: linux
    env: NODE_VERSION=6.9 CC=gcc-4.8 CXX=g++-4.8 DEBUG="electron-packager:*" INSTALL_TARGET=client
  - os: osx
    env: NODE_VERSION=6.9 CC=clang CXX=clang++ SIGN_BUILD=true DEBUG="electron-packager:*" INSTALL_TARGET=client
install:
- git clone https://github.com/creationix/nvm.git /tmp/.nvm
- source /tmp/.nvm/nvm.sh
- nvm install $NODE_VERSION
- nvm use --delete-prefix $NODE_VERSION
script:
- npm install && npm run build-client
- 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
 security delete-keychain -p travis nml-build.keychain
 security create-keychain -p travis nml-build.keychain
 security default-keychain -s nml-build.keychain
 security unlock-keychain -p travis nml-build.keychain
 security import ~/build/GrayW/nylas-mail/certs/AppleWWDRCA.cer -k ~/Library/Keychains/nml-build.keychain -T /usr/bin/codesign
 security import ~/build/GrayW/nylas-mail/certs/gray-nml.cer -k ~/Library/Keychains/nml-build.keychain -T /usr/bin/codesign
 security import ~/build/GrayW/nylas-mail/certs/gray-nml.p12 -k ~/Library/Keychains/nml-build.keychain -P $CERTIFICATE_PASSWORD -T /usr/bin/codesign;
 security set-key-partition-list -S apple-tool:, apple: -s -k travis nml-build.keychain
 fi' 
cache:
  directories:
  - node_modules
  - apm/node_modules