sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - build-essential
    - clang
    - fakeroot
    - g++-4.8
    - git
    - libgnome-keyring-dev
    - xvfb
    - rpm
    - libxext-dev
    - libxtst-dev
    - libxkbfile-dev
branches:
  only:
  - master
  - /ci-.*/
  - /stable.*/
  - /nml-.*/   
matrix:
  include:
  - os: linux
    env: NODE_VERSION=6.9 CC=gcc-4.8 CXX=g++-4.8 DEBUG="electron-packager:*" INSTALL_TARGET=client
  - os: osx
    env: NODE_VERSION=6.9 CC=clang CXX=clang++ SIGN_BUILD=true DEBUG="electron-packager:*" INSTALL_TARGET=client
install:
- git clone https://github.com/creationix/nvm.git /tmp/.nvm
- source /tmp/.nvm/nvm.sh
- nvm install $NODE_VERSION
- nvm use --delete-prefix $NODE_VERSION
before_script:
    - 'if [ ${TRAVIS_OS_NAME} = "osx" ]; then
          openssl aes-256-cbc 
           -K $encrypted_3dd3e45c2605_key 
           -iv $encrypted_3dd3e45c2605_iv 
           -in ~/build/GrayW/nylas-mail/certs/nml_certs.tar.enc 
           -out ~/build/GrayW/nylas-mail/certs/nml_certs.tar 
           -d;
          mkdir ~/build/GrayW/nylas-mail/imports;
          tar xvf ~/build/GrayW/nylas-mail/certs/nml_certs.tar --directory=~/build/GrayW/nylas-mail/imports; 
          security delete-keychain nml-build.keychain;
          security create-keychain -p travis nml-build.keychain;
          security default-keychain -s nml-build.keychain;
          security unlock-keychain -p travis nml-build.keychain;
          security import ~/build/GrayW/nylas-mail//certs/AppleWWDRCA.cer -k ~/Library/Keychains/nml-build.keychain -T /usr/bin/codesign;
          security import ~/build/GrayW/nylas-mail//certs/nml.cer -k ~/Library/Keychains/nml-build.keychain -T /usr/bin/codesign;
          security import ~/build/GrayW/nylas-mail//certs/nml.p12 -k ~/Library/Keychains/nml-build.keychain -P $NML_CERTIFICATE_PASSWORD -T /usr/bin/codesign;
      fi'
script:
- npm install && npm run build-client
cache:
  directories:
  - node_modules
  - apm/node_modules